### ISSUE TITLE
[Feat] ImageThread

### ISSUE THREAD

**Issue by angel-penchev** [braind3d/DRUN#4]
**Describe the feature you'd like**
Custom thread class for handling image input/output.

**Additional context**
It should invoke a selection of the following functions in separate threads:
- [x] __camera_input__: Reads data from the drone camera and stores it in the shared buffer.
- [x] __network_input__: Creates a socket for listening for received drone image frames.
- [x] __debug_output__: Creates a debug window for previewing the image data.
- [x] __network_output__: Connects to a given socket and forwards images to it.

**Comment by simo1209** [comment]
Will refactor communication to use websockets after HackTUES is over.

**Comment by simo1209** [comment]
I swear to never again send camera frames through plain old sockets.
